# MicroPython configuration for mp_fresh project
# Avoid forbidden imports; keep constants simple.

SMOKE_TEST = False

# Pin assignments
ULTRASONIC_PINS = {
    "trig": 18,
    "echo": 19,
}

FLOW_PIN = 5
DS18B20_PIN = 4
I2C_SDA = 21
I2C_SCL = 22
SHT3X_ADDR = 0x44

UART2_TX = 17
UART2_RX = 16
UART_BAUD = 9600

PRESET_CLEAR_DISTANCE_CM = 100.0
SNOW_THRESHOLD_CM = 5.0
SNOW_CLEAR_CM = 1.0
TARGET_TEMP_C = 36.0
PAVEMENT_CLEAR_C = 0.7

TILTED_MAX_ANGLE = 40
NON_TILTED_TARGETS = [
    TARGET_TEMP_C,
    TARGET_TEMP_C * 1.05,
    TARGET_TEMP_C * 1.10,
    TARGET_TEMP_C * 1.15,
    TARGET_TEMP_C * 0.95,
    TARGET_TEMP_C * 0.90,
    TARGET_TEMP_C * 0.85,
]

FLOW_WINDOW_MS = 1500
FLOW_DEBOUNCE_US = 2000

TRIAL_REST_SECONDS = 20 * 60
TRIAL_MAX_SECONDS = 15 * 60
LOG_INTERVAL_SECONDS = 10

BIN_WIDTH_TEMP = 4
BIN_WIDTH_HUM = 3
BIN_WIDTH_WIND_SPEED = 3
BIN_WIDTH_WIND_DIR = 3

STATE_PATH = "state/bin_counts.json"
LOG_DIR = "logs"

# Actuator motion estimate
DEGREE_PER_SECOND = 5

# Stub values
STUB_ULTRASONIC_CM = 100.0
STUB_FLUID_TEMP_C = 25.0
STUB_AMBIENT = (2.0, 60.0)
STUB_FLOW_PULSES_PER_WINDOW = 0
STUB_WIND = (1.0, 90)
STUB_PAVEMENT_TEMP_C = 0.2
