"""Configuration constants for the Aurora ESP32 snowmelt rig."""

# Hardware pins (GPIO numbers)
UART_ID = 2
UART_BAUD = 9600
UART_TX = 17
UART_RX = 16

ULTRASONIC_TRIG = 18
ULTRASONIC_ECHOS = [13, 12, 14, 19]
ULTRASONIC_TIMEOUT_US = 30000
ULTRASONIC_RETRIES = 3
ULTRASONIC_PING_GAP_MS = 80
ULTRASONIC_MIN_CM = 2.0
ULTRASONIC_MAX_CM = 400.0

DS18B20_PIN = 4
EXPECTED_DS18B20_COUNT = 12

I2C_ID = 0
I2C_SDA = 21
I2C_SCL = 22
SHT_ADDRESSES = [0x44, 0x45]
SHT_CMD_SINGLE_SHOT = b"\x24\x00"

# Actuator timing
FULL_TRAVEL_ANGLE_DEG = 45.0
FULL_TRAVEL_TIME_S = 8.0
HOME_TIME_S = 9.5

# Snow depth reference
MOUNT_HEIGHT_CM = 70.0
DEPTH_THRESHOLD_CM = 5.0
MELT_COMPLETE_CM = 0.5
MELT_STREAK_REQUIRED = 6

# Temperature targets
SLOPED_TARGET_FLUID_C = 26.0
NON_SLOPED_BASE_C = 30.0
NON_SLOPED_STEP_C = 3.0
NON_SLOPED_REPEAT = 5
HEATER_BAND_C = 2.0

# Timing
LOG_INTERVAL_S = 10
WAIT_BETWEEN_TESTS_S = 20 * 60
UPLOAD_TIMEOUT_S = 2
FINAL_UPLOAD_TIMEOUT_S = 300

# Wi-Fi / API (placeholders for MicroPython environment)
WIFI_SSID = "YOUR_WIFI"
WIFI_PASS = "YOUR_PASSWORD"
WEATHER_URL = "https://example.com/weather"
WEATHER_TIMEOUT_S = 4
WEATHER_CACHE_S = 300

# Logging
LOG_LEVEL = 2
LOG_DIR = "logs"

# Safety
ABORT_IF_NO_FLUID = True

# Misc
BUILD_ID = "aurora-micropython"
